---
metadata:
  name: "DXNN Test Environment"
  description: "Deploy the DXNN_test_v2 neural network system"
  version: "1.0"

aws:
  instance_type: "t2.micro"
  region: "us-east-1"
  
application:
  type: "dxnn"
  setup_commands:
    # Install Erlang/OTP and development tools
    - "yum groupinstall -y 'Development Tools'"
    - "yum install -y erlang git vim htop tree"
    # Create workspace directory
    - "mkdir -p /home/ec2-user/dxnn-workspace"
    - "chown ec2-user:ec2-user /home/ec2-user/dxnn-workspace"
    # Note: You can manually copy your DXNN files after SSH connection
  
networking:
  ports:
    - 22    # SSH
    - 4369  # Erlang Port Mapper Daemon (epmd)
    - 9100  # Custom Erlang application port
    - 9101  # Additional port for distributed Erlang
    - 8080  # Web interface (if you add one)

security:
  # Restrict access to your IP only (recommended)
  # ssh_cidr: "YOUR_IP/32"  # Uncomment and replace with your IP
  ssh_cidr: "0.0.0.0/0"     # Open to all (less secure but convenient)

tags:
  Project: "DXNN"
  Environment: "Development"
  Purpose: "Neural Network Testing"
  Owner: "Developer"
