metadata:
  name: "DXNN Spot Instance"
  description: "DXNN with spot interruption handling"
  version: "1.0"

aws:
  instance_type: "c5.2xlarge"
  market_type: "spot"
  spot_max_price: "0.30"
  region: "us-east-1"
  availability_zone: "us-east-1a"
  ami_id: "ami-020cba7c55df1f615"
  ssh_user: "ubuntu"
  iam_instance_profile: "DXNN-Spot-Profile"
  instance_initiated_shutdown_behavior: "terminate"

spot_handling:
  enabled: true
  checkpoint_deadline_seconds: 60  # From IMDS detection
  poll_interval_seconds: 2
  s3_bucket: "dxnn-checkpoints"
  s3_prefix: "dxnn"
  job_id: "dxnn-training-001"  # REQUIRED when restore enabled
  container_name: "dxnn-app"
  erlang_node: "dxnn@127.0.0.1"
  erlang_cookie_file: "/var/lib/dxnn/.erlang.cookie"
  restore_from_s3_on_boot: true
  use_rebalance_recommendation: false  # Default OFF

application:
  type: "dxnn-spot"
  setup_commands:
    - "apt-get update -y"
    - "apt-get install -y erlang git vim htop tree build-essential tmux chrony util-linux"
    - "systemctl enable chrony && systemctl start chrony"
    - "curl -L https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq"
    - "mkdir -p /var/lib/dxnn/checkpoints /var/log /run"
    - "chmod 755 /var/lib/dxnn/checkpoints"
    - |
      set -e
      cd /home/ubuntu
      git clone https://github.com/qendro/DXNN-Trader-v2.git dxnn-trader
      chown -R ubuntu:ubuntu /home/ubuntu/dxnn-trader
      
      # Install new scripts
      cp /tmp/finalize_run.sh /usr/local/bin/finalize_run.sh
      cp /tmp/dxnn-wrapper.sh /usr/local/bin/dxnn-wrapper.sh
      chmod +x /usr/local/bin/finalize_run.sh /usr/local/bin/dxnn-wrapper.sh
      
      # Set environment variables for wrapper
      export S3_BUCKET="dxnn-checkpoints"
      export S3_PREFIX="dxnn"
      export JOB_ID="dxnn-training-001"
      export RUN_ID="$(date -u +%Y%m%d-%H%M%SZ)"
      
      # Start DXNN with wrapper (replaces tmux startup)
      su - ubuntu -c '
        export S3_BUCKET="dxnn-checkpoints"
        export S3_PREFIX="dxnn"
        export JOB_ID="dxnn-training-001"
        export RUN_ID="$(date -u +%Y%m%d-%H%M%SZ)"
        /usr/local/bin/dxnn-wrapper.sh
      '

networking:
  ports:
    - 22
    - 4369
    - 9100

tags:
  Project: "DXNN-Spot"
  Environment: "Production"
  JobId: "dxnn-training-001"
