metadata:
  name: "DXNN Erlang Environment"
  description: "Erlang latest (Ubuntu) with DXNN Trader full setup"
  version: "1.0"

aws:
  #instance_type: "t2.micro"
  instance_type: "c7a.4xlarge"
  market_type: "spot"                     # ← Use Spot pricing
  spot_max_price: "0.30"                  # ← Optional: max hourly price in USD
  region: "us-east-1"
  availability_zone: "us-east-1a"
  ami_id: "ami-020cba7c55df1f615"   # Ubuntu Server 24.04 LTS, 64-bit (x86)
  ssh_user: "ubuntu"

application:
  type: "erlang"
  setup_commands:
  - "apt-get update -y"
  - "apt-get install -y erlang git vim htop tree build-essential tmux"

  - |
    set -e
    cd /home/ubuntu
    git clone -b tradeBot-001 https://github.com/qendro/DXNN-Trader-v2.git dxnn-trader
    chown -R ubuntu:ubuntu /home/ubuntu/dxnn-trader
    su - ubuntu -c '
      cd /home/ubuntu/dxnn-trader
      tmux new-session -d -s trader bash -c "  
        erl -noshell -eval \"
          mnesia:create_schema([node()]),
          mnesia:start(),
          make:all(),
          fx:init(),
          fx:start(),
          timer:sleep(5000),
          polis:create(),
          polis:start(),
          polis:sync(),
          benchmarker:start(sliding_window_5)
        \"
      "
    '

networking:
  ports:
    - 22
    - 4369
    - 9100

tags:
  Project: "DXNN-Trader"
  Environment: "Development"
  Purpose: "DXNN Erlang Trader Environment"
