---
metadata:
  name: "Generic Erlang Environment"
  description: "Basic Erlang/OTP development environment"
  version: "1.0"

aws:
  instance_type: "t2.micro"
  region: "us-east-1"
  ami_id: "ami-020cba7c55df1f615"   # Ubuntu Server 24.04 LTS, 64-bit (x86)
  ssh_user: "ubuntu"                # "ec2-user", "ubuntu", "admin", "debian", "root"
  
application:
  type: "erlang"
  setup_commands:
  # Update and install prerequisites
  - "apt-get update -y"
  - "apt-get install -y erlang-base git vim htop tree build-essential"
  # Create development workspace
  - "mkdir -p /home/ubuntu/erlang-workspace"
  - "chown ubuntu:ubuntu /home/ubuntu/erlang-workspace"
  
networking:
  ports:
    - 22    # SSH
    - 4369  # Erlang Port Mapper Daemon (epmd)
    - 9100  # Custom Erlang application port

tags:
  Project: "Erlang"
  Environment: "Development"
  Purpose: "Erlang Development"
